User/vsiliush/fix thumb hit area
microsoft/microsoft-ui-xaml pull request #4031
Opened 2021-01-27 02:21 UTC by beervoley

## Description

This PR increases the hit area of the thumb to the track size and adds a small margin on all the sides of the ScrollBar.

## Motivation and Context

Hit area of the thumb was too small (the thumb itself), making it very difficult to grab the thumb. This PR will increase it to the size of the Track.
There is also a new margin added on the scroll bar to create a space between the scrollbar and the window.
## How Has This Been Tested?

Manually
## Screenshots (if appropriate):

![image](https://user-images.githubusercontent.com/21356912/105933248-f6198200-6002-11eb-9469-a170322c2344.png)
![image](https://user-images.githubusercontent.com/21356912/105933260-f9ad0900-6002-11eb-8f25-89b744bd0e66.png)

2021-01-27 02:22 UTC, beervoley commented
/azp run

2021-01-27 08:32 UTC, beervoley commented
/azp run

2021-01-27 17:41 UTC, RBrid requested changes

2021-01-27 17:41 UTC, RBrid commented on dev/ScrollBar/ScrollBar_themeresources.xaml
> +                                           StrokeThickness="{Binding BorderThickness.Left, RelativeSource={RelativeSource TemplatedParent}}"
For consistency I would expect BorderThickness.Top to be used here.

2021-01-27 17:41 UTC, RBrid commented on dev/ScrollBar/ScrollBar_themeresources.xaml
> +    <Thickness x:Key="ScrollBarThumbBorderThickness">6,6,6,6</Thickness>
ScrollBarMargin shows me that you could use 
`<Thickness x:Key="ScrollBarThumbBorderThickness">6</Thickness>`

2021-01-27 17:41 UTC, RBrid commented on dev/ScrollBar/ScrollBar_themeresources.xaml
> +    <CornerRadius x:Key="ScrollBarTrackCornerRadius">6,6,6,6</CornerRadius>
`<CornerRadius x:Key="ScrollBarTrackCornerRadius">6</CornerRadius>`  works too.  

(same for ScrollBarCornerRadius)

2021-01-27 17:51 UTC, karenbtlai commented on dev/ScrollBar/ScrollBar_themeresources.xaml
> +        <Setter Property="Margin" Value="{StaticResource ScrollBarMargin}"/>
nit: I would move the margin setter under MinHeight to group the StaticResources together

2021-01-27 22:26 UTC, marksfoster approved these changes

2021-01-28 00:15 UTC, beervoley commented
I fixed the issues outlined in comments but still cannot resolve InfoBar crashes. Will continue tomorrow.

2021-01-28 00:15 UTC, beervoley commented
/azp run

2021-01-28 07:21 UTC, beervoley commented
Removed binding to strokeThickness.
1) Binding to any value of Thickness to extract a Double for StrokeThickness  produces a weird error with duplicated key in dictionary and causes InfoBar to crash (not sure why that happens, needs investigation).
2) Since Thickness is a struct, after we bind to value like Thickness.Top - it won't be updated because it's not a dependency property. 

The best way to solve this issue is to create a converter from Thickness to Double. For now, I've just binded the StrokeThickness to StaticResource but it's not ideal. I will open an issue about this.

2021-01-28 07:22 UTC, beervoley commented
/azp run

2021-01-28 16:44 UTC, beervoley commented
/azp run

2021-01-28 19:11 UTC, beervoley commented
/azp run

2021-01-29 05:25 UTC, beervoley commented
/azp run

2021-01-29 06:48 UTC, beervoley commented
/azp run

2021-02-02 03:40 UTC, beervoley commented
/azp run

2021-02-02 05:34 UTC, beervoley commented
/azp run

2021-02-02 19:16 UTC, beervoley commented
/azp run

2021-02-02 21:33 UTC, RBrid approved these changes

2021-02-02 21:34 UTC, merged