MediaPlayerElement fluent updates (partial fix)
microsoft/microsoft-ui-xaml pull request #4877
Opened 2021-04-21 19:33 UTC by kimsealls

## Description
Fixed:
- Updated background to in-app acrylic
- Updated appbar button sizes to 40px, both command bar and flyout
- Removed height properties on the button and commandbar to allow proper content flow (with this property, buttons appear too short)
Not fixed (needs advanced work):
- Right appbar button clipping
- New style of slider
- Inset background with rounded corners and shadow

## Motivation and Context
This updates elements to new style and fixes visually broken button backplates

## How Has This Been Tested?
WinUI test app

## Screenshots (if appropriate):

![MTC_before_rest](https://user-images.githubusercontent.com/42077683/115610237-6e5bb080-a29d-11eb-9e07-38266447fe84.PNG)
![MTC_before_hover](https://user-images.githubusercontent.com/42077683/115610242-70257400-a29d-11eb-9ca8-8fe6f46ac5de.PNG)

![MTC_after_rest](https://user-images.githubusercontent.com/42077683/115610240-6f8cdd80-a29d-11eb-940b-259a1a282936.PNG)
![MTC_after_hover](https://user-images.githubusercontent.com/42077683/115610239-6ef44700-a29d-11eb-9eb0-b156cf4c9b05.PNG)

2021-04-21 19:49 UTC, marksfoster approved these changes

2021-04-21 19:50 UTC, marksfoster commented
/azp run

2021-04-22 22:52 UTC, StephenLPeters commented on dev/CommonStyles/MediaTransportControls_themeresources.xaml
> +    <x:Double x:Key="MediaTransportControlsAppBarButtonSize">40</x:Double>
>MediaTransportControlsAppBarButtonSize [](http://example.com/codeflow?start=21&length=38)

This change has some compatability concerns.  If a developer was overriding the MTCMediaButtonWidth and MTCMediaButtonHeight resources to customize their MTC then this change would stop that from working.  I would suggest instead we provide a Winui2 value for MTCMediaButtonWidth and MTCMediaButtonHeight in the ThemeDictionaries above.

2021-04-22 22:53 UTC, StephenLPeters requested changes
:clock1:

2021-06-08 15:48 UTC, closed without merging