Fix issue where pips pagers crash when the next or previous arrow button is clicked in RTL flow direction
microsoft/microsoft-ui-xaml pull request #6607
Opened 2022-01-14 19:55 UTC by StephenLPeters

FontIcon has code in it that sets a render transform on itself when the flow direction is RTL and the MirroredWhenRIghtToLeft is set to true, in order to mirror the icon using a -1 x-dimension scale.  However the PipsPagerNavigationButtonBaseStyle sets a scale transform on the font icon in order to decrease the size of the icon in the pressed state.  This is done by referencing the scale transform by name.  However the font icon code is overriding the named scale transform with an unnammed one, resulting in a crash when the storyboard tries to reference the named scale transform.  We could work around this by referencing the scale transform by property rather than by name, but then we would need to manage the mirrored when RTL scale of -1 ourselves.  Instead I've separated the two scale transforms.

2022-01-14 19:56 UTC, StephenLPeters commented
/azp run

2022-01-27 20:03 UTC, kmahone commented on test/testinfra/MUXTestInfra/Infra/TestHelpers.cs
Is this used anywhere?

2022-01-27 20:03 UTC, kmahone requested changes
:clock1:

2022-02-03 20:00 UTC, StephenLPeters commented on dev/PipsPager/InteractionTests/PipsPagerTests.cs
> +                TestSetupHelper.SetInnerFrameFlowDirection(FlowDirection.RightToLeft);
@kmahone here

2022-02-03 20:12 UTC, kmahone approved these changes
:shipit:

2022-02-04 00:33 UTC, StephenLPeters commented
/azp run

2022-02-04 03:28 UTC, StephenLPeters commented
/azp run

2022-02-04 06:24 UTC, StephenLPeters commented
/azp run

2022-02-04 17:26 UTC, merged